name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create zip
        run: zip -r ./build/release.zip .

      - name: FTP Deployer
        # You may pin to the exact commit or the version.
        # uses: sand4rt/ftp-deployer@b0fc0a8e0336dddf2192e4415062ad00bd533cba
        uses: sand4rt/ftp-deployer@v1.7
        with:
          host: 'ftp.fennech.io'
          port: 22
          username: 'test@fennech.io'
          # Ftp password
          password: '4@1E#@5h2sth'
          local_folder: './build'
